-- Migration: Seed marketplace items for template marketplace
-- Description: Initial curated templates and landing pages by specialty (general, dentistry, nutrition)
-- Author: Claude
-- Date: 2026-02-17

-- ============================================================================
-- GENERAL SPECIALTY — pt-BR
-- ============================================================================

INSERT INTO public.marketplace_items (type, title, description, content, specialty, locale, thumbnail_url) VALUES
('template', 'Resumo da Consulta', 'Template para resumos de consultas médicas com seções de exame, achados, tratamentos e recomendações.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Resumo da Consulta</mark></strong></p><p></p><p><strong>Paciente:</strong> $patient.fullName$</p><p><strong>Profissional:</strong> $me.fullName$</p><p><strong>Data:</strong> $session.created_at$</p><p></p><p><strong>Motivo da Consulta</strong></p><p>[Descreva o motivo principal da consulta e queixas apresentadas pelo paciente.]</p><p></p><p><strong>Exame Clínico</strong></p><p>[Descreva os achados do exame físico, incluindo sinais vitais e observações relevantes.]</p><p></p><p><strong>Diagnóstico</strong></p><p>[Liste os diagnósticos identificados durante a consulta.]</p><p></p><p><strong>Conduta</strong></p><p>[Descreva o plano de tratamento, medicações prescritas e orientações dadas ao paciente.]</p><p></p><p><strong>Retorno</strong></p><p>- Próxima consulta: [Data ou período recomendado]</p><p>- Exames solicitados: [Liste exames pendentes]</p><p></p><p>Atenciosamente,</p><p>$me.fullName$</p>', 'general', 'pt-BR', null),

('template', 'Nota Clínica Geral', 'Template completo para notas clínicas com anamnese, exame, diagnóstico e plano terapêutico.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Nota Clínica</mark></strong></p><p></p><p>Dr(a). $me.fullName$ atendeu $patient.fullName$ em $session.created_at$.</p><p></p><p><strong>Anamnese</strong></p><p>[Queixa principal, história da doença atual, antecedentes pessoais e familiares.]</p><p></p><p><strong>Exame Físico</strong></p><p>- Estado geral: [Descrição]</p><p>- Sinais vitais: PA: [___] FC: [___] FR: [___] Temp: [___]</p><p>- Exame segmentar: [Achados por sistemas]</p><p></p><p><strong>Hipóteses Diagnósticas</strong></p><p>[Liste as hipóteses diagnósticas consideradas.]</p><p></p><p><strong>Plano Terapêutico</strong></p><p>[Medicações, procedimentos, encaminhamentos e orientações.]</p><p></p><p><strong>Observações</strong></p><p>[Informações adicionais relevantes.]</p>', 'general', 'pt-BR', null);

-- ============================================================================
-- GENERAL SPECIALTY — en-US
-- ============================================================================

INSERT INTO public.marketplace_items (type, title, description, content, specialty, locale, thumbnail_url) VALUES
('template', 'Consultation Summary', 'Template for medical consultation summaries with examination, findings, treatments and recommendations.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Consultation Summary</mark></strong></p><p></p><p><strong>Patient:</strong> $patient.fullName$</p><p><strong>Provider:</strong> $me.fullName$</p><p><strong>Date:</strong> $session.created_at$</p><p></p><p><strong>Reason for Visit</strong></p><p>[Describe the main reason for the consultation and patient complaints.]</p><p></p><p><strong>Clinical Examination</strong></p><p>[Describe physical exam findings, including vital signs and relevant observations.]</p><p></p><p><strong>Diagnosis</strong></p><p>[List diagnoses identified during the consultation.]</p><p></p><p><strong>Treatment Plan</strong></p><p>[Describe the treatment plan, prescribed medications, and patient instructions.]</p><p></p><p><strong>Follow-Up</strong></p><p>- Next appointment: [Recommended date or timeframe]</p><p>- Ordered tests: [List pending tests]</p><p></p><p>Sincerely,</p><p>$me.fullName$</p>', 'general', 'en-US', null),

('template', 'General Clinical Note', 'Complete clinical note template with history, examination, diagnosis and treatment plan.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Clinical Note</mark></strong></p><p></p><p>Dr. $me.fullName$ saw $patient.fullName$ on $session.created_at$.</p><p></p><p><strong>History</strong></p><p>[Chief complaint, history of present illness, past medical and family history.]</p><p></p><p><strong>Physical Examination</strong></p><p>- General: [Description]</p><p>- Vitals: BP: [___] HR: [___] RR: [___] Temp: [___]</p><p>- Systems review: [Findings by system]</p><p></p><p><strong>Assessment</strong></p><p>[List diagnostic considerations.]</p><p></p><p><strong>Plan</strong></p><p>[Medications, procedures, referrals and patient education.]</p><p></p><p><strong>Notes</strong></p><p>[Additional relevant information.]</p>', 'general', 'en-US', null);

-- ============================================================================
-- DENTISTRY SPECIALTY — pt-BR
-- ============================================================================

INSERT INTO public.marketplace_items (type, title, description, content, specialty, locale, thumbnail_url) VALUES
('template', 'Avaliação Odontológica', 'Template para avaliação odontológica inicial com exame intraoral, diagnóstico e plano de tratamento.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Avaliação Odontológica</mark></strong></p><p></p><p><strong>Paciente:</strong> $patient.fullName$</p><p><strong>Dentista:</strong> $me.fullName$</p><p><strong>Data:</strong> $session.created_at$</p><p></p><p><strong>Queixa Principal</strong></p><p>[Motivo da consulta e sintomas relatados pelo paciente.]</p><p></p><p><strong>Exame Intraoral</strong></p><p>- Tecidos moles: [Mucosa, gengiva, língua, palato]</p><p>- Periodonto: [Sondagem, mobilidade, sangramento]</p><p>- Dentição: [Cáries, restaurações, ausências]</p><p>- Oclusão: [Classificação, interferências]</p><p>- ATM: [Abertura, ruídos, dor]</p><p></p><p><strong>Exames Complementares</strong></p><p>[Radiografias solicitadas/avaliadas e achados.]</p><p></p><p><strong>Diagnóstico</strong></p><p>[Diagnósticos odontológicos identificados por dente/região.]</p><p></p><p><strong>Plano de Tratamento</strong></p><p>1. [Procedimento — dente/região — prioridade]</p><p>2. [Procedimento — dente/região — prioridade]</p><p>3. [Procedimento — dente/região — prioridade]</p><p></p><p><strong>Orientações ao Paciente</strong></p><p>[Higiene oral, cuidados pós-procedimento, alimentação.]</p><p></p><p><strong>Próxima Sessão</strong></p><p>[Data e procedimento planejado.]</p>', 'dentistry', 'pt-BR', null),

('template', 'Nota de Procedimento Odontológico', 'Template para registro de procedimentos odontológicos realizados durante a sessão.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Nota de Procedimento</mark></strong></p><p></p><p><strong>Paciente:</strong> $patient.fullName$</p><p><strong>Dentista:</strong> $me.fullName$</p><p><strong>Data:</strong> $session.created_at$</p><p></p><p><strong>Procedimento Realizado</strong></p><p>[Descreva o procedimento, dente(s) tratado(s), técnica utilizada e materiais empregados.]</p><p></p><p><strong>Anestesia</strong></p><p>[Tipo de anestésico, técnica, quantidade e região anestesiada.]</p><p></p><p><strong>Intercorrências</strong></p><p>[Descreva qualquer intercorrência durante o procedimento ou indique "Sem intercorrências".]</p><p></p><p><strong>Orientações Pós-Operatórias</strong></p><p>- Medicação: [Prescrições e posologia]</p><p>- Cuidados: [Orientações específicas de pós-operatório]</p><p>- Alimentação: [Restrições alimentares temporárias]</p><p></p><p><strong>Retorno</strong></p><p>[Data de retorno e motivo — reavaliação, continuidade do tratamento.]</p>', 'dentistry', 'pt-BR', null);

-- ============================================================================
-- DENTISTRY SPECIALTY — en-US
-- ============================================================================

INSERT INTO public.marketplace_items (type, title, description, content, specialty, locale, thumbnail_url) VALUES
('template', 'Dental Assessment', 'Template for initial dental assessment with intraoral exam, diagnosis and treatment plan.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Dental Assessment</mark></strong></p><p></p><p><strong>Patient:</strong> $patient.fullName$</p><p><strong>Dentist:</strong> $me.fullName$</p><p><strong>Date:</strong> $session.created_at$</p><p></p><p><strong>Chief Complaint</strong></p><p>[Reason for visit and symptoms reported by the patient.]</p><p></p><p><strong>Intraoral Examination</strong></p><p>- Soft tissues: [Mucosa, gingiva, tongue, palate]</p><p>- Periodontal: [Probing, mobility, bleeding]</p><p>- Dentition: [Caries, restorations, missing teeth]</p><p>- Occlusion: [Classification, interferences]</p><p>- TMJ: [Opening, sounds, pain]</p><p></p><p><strong>Diagnostic Imaging</strong></p><p>[Radiographs ordered/evaluated and findings.]</p><p></p><p><strong>Diagnosis</strong></p><p>[Dental diagnoses identified by tooth/region.]</p><p></p><p><strong>Treatment Plan</strong></p><p>1. [Procedure — tooth/region — priority]</p><p>2. [Procedure — tooth/region — priority]</p><p>3. [Procedure — tooth/region — priority]</p><p></p><p><strong>Patient Instructions</strong></p><p>[Oral hygiene, post-procedure care, dietary guidance.]</p><p></p><p><strong>Next Appointment</strong></p><p>[Date and planned procedure.]</p>', 'dentistry', 'en-US', null),

('template', 'Dental Procedure Note', 'Template for recording dental procedures performed during the session.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Procedure Note</mark></strong></p><p></p><p><strong>Patient:</strong> $patient.fullName$</p><p><strong>Dentist:</strong> $me.fullName$</p><p><strong>Date:</strong> $session.created_at$</p><p></p><p><strong>Procedure Performed</strong></p><p>[Describe the procedure, tooth/teeth treated, technique used and materials employed.]</p><p></p><p><strong>Anesthesia</strong></p><p>[Anesthetic type, technique, dosage and region anesthetized.]</p><p></p><p><strong>Complications</strong></p><p>[Describe any complications during the procedure or note "No complications".]</p><p></p><p><strong>Post-Operative Instructions</strong></p><p>- Medication: [Prescriptions and dosage]</p><p>- Care: [Specific post-operative instructions]</p><p>- Diet: [Temporary dietary restrictions]</p><p></p><p><strong>Follow-Up</strong></p><p>[Return date and reason — re-evaluation, treatment continuation.]</p>', 'dentistry', 'en-US', null);

-- ============================================================================
-- NUTRITION SPECIALTY — pt-BR
-- ============================================================================

INSERT INTO public.marketplace_items (type, title, description, content, specialty, locale, thumbnail_url) VALUES
('template', 'Avaliação Nutricional', 'Template para avaliação nutricional com anamnese alimentar, antropometria e plano alimentar.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Avaliação Nutricional</mark></strong></p><p></p><p><strong>Paciente:</strong> $patient.fullName$</p><p><strong>Nutricionista:</strong> $me.fullName$</p><p><strong>Data:</strong> $session.created_at$</p><p></p><p><strong>Motivo da Consulta</strong></p><p>[Objetivo do paciente: emagrecimento, ganho de massa, reeducação alimentar, patologia específica.]</p><p></p><p><strong>Anamnese Alimentar</strong></p><p>- Recordatório 24h: [Descreva as refeições do dia anterior]</p><p>- Preferências: [Alimentos preferidos e rejeitados]</p><p>- Restrições: [Alergias, intolerâncias, restrições religiosas/culturais]</p><p>- Suplementos: [Suplementos em uso]</p><p>- Hidratação: [Ingestão diária de água]</p><p></p><p><strong>Antropometria</strong></p><p>- Peso: [___] kg</p><p>- Altura: [___] m</p><p>- IMC: [___] kg/m²</p><p>- Circunferência abdominal: [___] cm</p><p>- % Gordura corporal: [___]%</p><p></p><p><strong>Exames Laboratoriais</strong></p><p>[Resultados de exames relevantes: glicemia, colesterol, triglicerídeos, etc.]</p><p></p><p><strong>Diagnóstico Nutricional</strong></p><p>[Estado nutricional e classificação.]</p><p></p><p><strong>Plano Alimentar</strong></p><p>[Objetivo calórico, distribuição de macronutrientes e orientações gerais.]</p><p></p><p><strong>Orientações</strong></p><p>[Recomendações de estilo de vida, atividade física e hábitos alimentares.]</p><p></p><p><strong>Retorno</strong></p><p>[Data e objetivos para a próxima consulta.]</p>', 'nutrition', 'pt-BR', null),

('template', 'Evolução Nutricional', 'Template para acompanhamento e evolução de pacientes em tratamento nutricional.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Evolução Nutricional</mark></strong></p><p></p><p><strong>Paciente:</strong> $patient.fullName$</p><p><strong>Nutricionista:</strong> $me.fullName$</p><p><strong>Data:</strong> $session.created_at$</p><p></p><p><strong>Adesão ao Plano</strong></p><p>[Avalie a adesão do paciente ao plano alimentar anterior, dificuldades encontradas e ajustes realizados.]</p><p></p><p><strong>Evolução Antropométrica</strong></p><p>- Peso atual: [___] kg (anterior: [___] kg)</p><p>- Variação: [+/-___] kg</p><p>- IMC atual: [___]</p><p>- Circunferência abdominal: [___] cm</p><p></p><p><strong>Sintomas e Queixas</strong></p><p>[Sintomas gastrointestinais, energia, sono, humor e outros relatos.]</p><p></p><p><strong>Ajustes no Plano</strong></p><p>[Mudanças realizadas no plano alimentar com justificativa.]</p><p></p><p><strong>Metas para Próximo Período</strong></p><p>[Objetivos específicos e mensuráveis até a próxima consulta.]</p><p></p><p><strong>Retorno</strong></p><p>[Data da próxima consulta.]</p>', 'nutrition', 'pt-BR', null);

-- ============================================================================
-- NUTRITION SPECIALTY — en-US
-- ============================================================================

INSERT INTO public.marketplace_items (type, title, description, content, specialty, locale, thumbnail_url) VALUES
('template', 'Nutritional Assessment', 'Template for nutritional assessment with dietary history, anthropometry and meal plan.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Nutritional Assessment</mark></strong></p><p></p><p><strong>Patient:</strong> $patient.fullName$</p><p><strong>Nutritionist:</strong> $me.fullName$</p><p><strong>Date:</strong> $session.created_at$</p><p></p><p><strong>Reason for Visit</strong></p><p>[Patient goals: weight loss, muscle gain, dietary reeducation, specific condition.]</p><p></p><p><strong>Dietary History</strong></p><p>- 24h recall: [Describe meals from the previous day]</p><p>- Preferences: [Preferred and disliked foods]</p><p>- Restrictions: [Allergies, intolerances, religious/cultural restrictions]</p><p>- Supplements: [Current supplements]</p><p>- Hydration: [Daily water intake]</p><p></p><p><strong>Anthropometry</strong></p><p>- Weight: [___] kg</p><p>- Height: [___] m</p><p>- BMI: [___] kg/m²</p><p>- Waist circumference: [___] cm</p><p>- Body fat %: [___]%</p><p></p><p><strong>Lab Results</strong></p><p>[Relevant lab results: glucose, cholesterol, triglycerides, etc.]</p><p></p><p><strong>Nutritional Diagnosis</strong></p><p>[Nutritional status and classification.]</p><p></p><p><strong>Meal Plan</strong></p><p>[Caloric target, macronutrient distribution and general guidelines.]</p><p></p><p><strong>Recommendations</strong></p><p>[Lifestyle, physical activity and dietary habit recommendations.]</p><p></p><p><strong>Follow-Up</strong></p><p>[Date and goals for next appointment.]</p>', 'nutrition', 'en-US', null),

('template', 'Nutritional Progress Note', 'Template for tracking nutritional treatment progress and follow-up.', '<p><strong><mark data-color="var(--tt-color-highlight-purple)" style="background-color: var(--tt-color-highlight-purple); color: inherit;">Nutritional Progress Note</mark></strong></p><p></p><p><strong>Patient:</strong> $patient.fullName$</p><p><strong>Nutritionist:</strong> $me.fullName$</p><p><strong>Date:</strong> $session.created_at$</p><p></p><p><strong>Plan Adherence</strong></p><p>[Evaluate patient adherence to previous meal plan, difficulties encountered and adjustments made.]</p><p></p><p><strong>Anthropometric Progress</strong></p><p>- Current weight: [___] kg (previous: [___] kg)</p><p>- Change: [+/-___] kg</p><p>- Current BMI: [___]</p><p>- Waist circumference: [___] cm</p><p></p><p><strong>Symptoms and Concerns</strong></p><p>[GI symptoms, energy, sleep, mood and other reports.]</p><p></p><p><strong>Plan Adjustments</strong></p><p>[Changes made to the meal plan with rationale.]</p><p></p><p><strong>Goals for Next Period</strong></p><p>[Specific, measurable objectives until next appointment.]</p><p></p><p><strong>Follow-Up</strong></p><p>[Next appointment date.]</p>', 'nutrition', 'en-US', null);

-- ============================================================================
-- LANDING PAGE TEMPLATES (one per specialty, pt-BR only initially)
-- ============================================================================

INSERT INTO public.marketplace_items (type, title, description, content, specialty, locale, thumbnail_url) VALUES
('landing_page', 'Landing Page — Clínica Geral', 'Template de landing page para clínicas e consultórios médicos gerais.', '{"root":{"props":{}},"zones":{},"content":[{"type":"Header","props":{"id":"Header-mkt-gen-01","height":"80","showLogo":true,"buttonUrl":"#","showButton":true,"buttonLabel":"Aprovar Proposta","buttonVariant":"primary","buttonAction":"approve_quote","backgroundColor":"white","buttonTextColor":"#ffffff"}},{"type":"Hero","props":{"id":"Hero-mkt-gen-01","align":"center","title":"Sua Proposta de Tratamento","buttons":[],"padding":"220px","titleSize":"64","titleColor":"#111827","description":"Confira os detalhes do seu plano de tratamento personalizado.","backgroundMode":"none","inlineMediaUrl":"","backgroundColor":"#f9fafb","descriptionSize":"22","inlineMediaType":"video","showInlineMedia":false,"descriptionColor":"default","backgroundOpacity":1,"backgroundImageUrl":"","disableVideoOnMobile":false}},{"type":"Space","props":{"id":"Space-mkt-gen-01","size":40,"direction":"vertical"}},{"type":"Flex","props":{"id":"Flex-mkt-gen-01","gap":40,"wrap":true,"direction":"column","justifyContent":"flex-start","backgroundColor":"none","verticalPadding":0,"horizontalPadding":16,"content":[{"type":"CardContainer","props":{"id":"CardContainer-mkt-gen-01","title":"Detalhes da Proposta","content":[{"type":"QuoteContent","props":{"id":"QuoteContent-mkt-gen-01"}}],"padding":"md","showTitle":false,"titleColor":"#111827","borderColor":"#e5e7eb","description":"","backgroundColor":"none","showDescription":false,"descriptionColor":"#4b5563"}},{"type":"Divider","props":{"id":"Divider-mkt-gen-01","color":"#e5e7eb","spacing":8,"thickness":1}},{"type":"QuoteNumber","props":{"id":"QuoteNumber-mkt-gen-01","size":"l","label":"Proposta #","showNumber":true}},{"type":"QuoteItems","props":{"id":"QuoteItems-mkt-gen-01","showPrice":false,"showDiscount":false}},{"type":"QuoteTotal","props":{"id":"QuoteTotal-mkt-gen-01","label":"Total","totalColor":"primary"}}]}},{"type":"Space","props":{"id":"Space-mkt-gen-02","size":40,"direction":"vertical"}},{"type":"Footer","props":{"id":"Footer-mkt-gen-01","contactSource":"branding","textColor":"#ffffff","socialTitle":"Redes Sociais","quickLinksTitle":"Links Rápidos","contactTitle":"Contato","quickLinks":[{"url":"#privacy","label":"Política de Privacidade"},{"url":"#terms","label":"Termos de Uso"},{"url":"#contact","label":"Contato"}],"showContact":true,"showEmail":true,"showPhone":true,"showAddress":true,"socialLinks":[{"url":"https://facebook.com","platform":"facebook"},{"url":"https://instagram.com","platform":"instagram"}],"contactItems":[{"type":"phone","value":"+55 (11) 1234-5678"},{"type":"email","value":"contato@clinica.com.br"},{"type":"address","value":"Av. Principal, 123 - São Paulo, SP"}],"copyrightText":"Copyright 2026 Todos os direitos reservados.","showQuickLinks":true,"backgroundColor":"dark","showSocialLinks":true,"verticalPadding":32,"horizontalPadding":16}}]}', 'general', 'pt-BR', null),

('landing_page', 'Landing Page — Odontologia', 'Template de landing page para clínicas e consultórios odontológicos.', '{"root":{"props":{}},"zones":{},"content":[{"type":"Header","props":{"id":"Header-mkt-dent-01","height":"80","showLogo":true,"buttonUrl":"#","showButton":true,"buttonLabel":"Aprovar Proposta","buttonVariant":"primary","buttonAction":"approve_quote","backgroundColor":"white","buttonTextColor":"#ffffff"}},{"type":"Hero","props":{"id":"Hero-mkt-dent-01","align":"center","title":"Seu Plano de Tratamento Odontológico","buttons":[],"padding":"220px","titleSize":"64","titleColor":"#111827","description":"Confira os detalhes do tratamento proposto para o seu sorriso.","backgroundMode":"none","inlineMediaUrl":"","backgroundColor":"#f0fdf4","descriptionSize":"22","inlineMediaType":"video","showInlineMedia":false,"descriptionColor":"default","backgroundOpacity":1,"backgroundImageUrl":"","disableVideoOnMobile":false}},{"type":"Space","props":{"id":"Space-mkt-dent-01","size":40,"direction":"vertical"}},{"type":"Flex","props":{"id":"Flex-mkt-dent-01","gap":40,"wrap":true,"direction":"column","justifyContent":"flex-start","backgroundColor":"none","verticalPadding":0,"horizontalPadding":16,"content":[{"type":"CardContainer","props":{"id":"CardContainer-mkt-dent-01","title":"","content":[{"type":"QuoteContent","props":{"id":"QuoteContent-mkt-dent-01"}}],"padding":"md","showTitle":false,"titleColor":"#111827","borderColor":"#e5e7eb","description":"","backgroundColor":"none","showDescription":false,"descriptionColor":"#4b5563"}},{"type":"Divider","props":{"id":"Divider-mkt-dent-01","color":"#e5e7eb","spacing":8,"thickness":1}},{"type":"QuoteNumber","props":{"id":"QuoteNumber-mkt-dent-01","size":"l","label":"Proposta #","showNumber":true}},{"type":"QuoteItems","props":{"id":"QuoteItems-mkt-dent-01","showPrice":false,"showDiscount":false}},{"type":"QuoteTotal","props":{"id":"QuoteTotal-mkt-dent-01","label":"Total","totalColor":"primary"}}]}},{"type":"Space","props":{"id":"Space-mkt-dent-02","size":40,"direction":"vertical"}},{"type":"Footer","props":{"id":"Footer-mkt-dent-01","contactSource":"branding","textColor":"#ffffff","socialTitle":"Redes Sociais","quickLinksTitle":"Links Rápidos","contactTitle":"Contato","quickLinks":[{"url":"#privacy","label":"Política de Privacidade"},{"url":"#terms","label":"Termos de Uso"},{"url":"#contact","label":"Contato"}],"showContact":true,"showEmail":true,"showPhone":true,"showAddress":true,"socialLinks":[{"url":"https://facebook.com","platform":"facebook"},{"url":"https://instagram.com","platform":"instagram"}],"contactItems":[{"type":"phone","value":"+55 (11) 1234-5678"},{"type":"email","value":"contato@odonto.com.br"},{"type":"address","value":"Rua dos Sorrisos, 456 - São Paulo, SP"}],"copyrightText":"Copyright 2026 Todos os direitos reservados.","showQuickLinks":true,"backgroundColor":"dark","showSocialLinks":true,"verticalPadding":32,"horizontalPadding":16}}]}', 'dentistry', 'pt-BR', null),

('landing_page', 'Landing Page — Nutrição', 'Template de landing page para consultórios de nutrição e alimentação saudável.', '{"root":{"props":{}},"zones":{},"content":[{"type":"Header","props":{"id":"Header-mkt-nut-01","height":"80","showLogo":true,"buttonUrl":"#","showButton":true,"buttonLabel":"Aprovar Proposta","buttonVariant":"primary","buttonAction":"approve_quote","backgroundColor":"white","buttonTextColor":"#ffffff"}},{"type":"Hero","props":{"id":"Hero-mkt-nut-01","align":"center","title":"Seu Plano Nutricional Personalizado","buttons":[],"padding":"220px","titleSize":"64","titleColor":"#111827","description":"Confira os detalhes do plano alimentar elaborado para você.","backgroundMode":"none","inlineMediaUrl":"","backgroundColor":"#fff7ed","descriptionSize":"22","inlineMediaType":"video","showInlineMedia":false,"descriptionColor":"default","backgroundOpacity":1,"backgroundImageUrl":"","disableVideoOnMobile":false}},{"type":"Space","props":{"id":"Space-mkt-nut-01","size":40,"direction":"vertical"}},{"type":"Flex","props":{"id":"Flex-mkt-nut-01","gap":40,"wrap":true,"direction":"column","justifyContent":"flex-start","backgroundColor":"none","verticalPadding":0,"horizontalPadding":16,"content":[{"type":"CardContainer","props":{"id":"CardContainer-mkt-nut-01","title":"","content":[{"type":"QuoteContent","props":{"id":"QuoteContent-mkt-nut-01"}}],"padding":"md","showTitle":false,"titleColor":"#111827","borderColor":"#e5e7eb","description":"","backgroundColor":"none","showDescription":false,"descriptionColor":"#4b5563"}},{"type":"Divider","props":{"id":"Divider-mkt-nut-01","color":"#e5e7eb","spacing":8,"thickness":1}},{"type":"QuoteNumber","props":{"id":"QuoteNumber-mkt-nut-01","size":"l","label":"Proposta #","showNumber":true}},{"type":"QuoteItems","props":{"id":"QuoteItems-mkt-nut-01","showPrice":false,"showDiscount":false}},{"type":"QuoteTotal","props":{"id":"QuoteTotal-mkt-nut-01","label":"Total","totalColor":"primary"}}]}},{"type":"Space","props":{"id":"Space-mkt-nut-02","size":40,"direction":"vertical"}},{"type":"Footer","props":{"id":"Footer-mkt-nut-01","contactSource":"branding","textColor":"#ffffff","socialTitle":"Redes Sociais","quickLinksTitle":"Links Rápidos","contactTitle":"Contato","quickLinks":[{"url":"#privacy","label":"Política de Privacidade"},{"url":"#terms","label":"Termos de Uso"},{"url":"#contact","label":"Contato"}],"showContact":true,"showEmail":true,"showPhone":true,"showAddress":true,"socialLinks":[{"url":"https://facebook.com","platform":"facebook"},{"url":"https://instagram.com","platform":"instagram"}],"contactItems":[{"type":"phone","value":"+55 (11) 1234-5678"},{"type":"email","value":"contato@nutri.com.br"},{"type":"address","value":"Rua Saudável, 789 - São Paulo, SP"}],"copyrightText":"Copyright 2026 Todos os direitos reservados.","showQuickLinks":true,"backgroundColor":"dark","showSocialLinks":true,"verticalPadding":32,"horizontalPadding":16}}]}', 'nutrition', 'pt-BR', null);
